#!/bin/bash

function clearTex(){
	echo "Ripulisco \"tex/\" ..."
	cd tex
	rm *~ *.aux *.dvi *.log *.pdf *.bbl *.blg *.toc *.out tesi-frn.tex
	cd ..
	echo "Fatto"
}

function clearGfx(){
	echo "Ripulisco \"graphics\" ..."
	cd graphics
	rm *-converted-to.pdf
	cd ..
	echo "Fatto"
}

function clearAll(){
	echo "Pulizie di primavera in corso ..."
	clearTex
	clearGfx
	echo "Ok, godiamoci il tepore primaverile"
}

function mkFrontespizio() {
	local name="front"
	local tmpDir="tmp"
	local filename="$name.tex"
	local srcDir="tex"
	local gfxDir="graphics"
	
	mkdir $tmpDir
	cp "$srcDir/frontespizio.tex" "$tmpDir"
	echo "
		\documentclass[12pt, a4paper, twoside, openright, titlepage]{book}
		\usepackage[utf8]{inputenc}
		\usepackage[italian]{babel}
		\usepackage{mathptmx}
		\usepackage{graphicx}
		\graphicspath{ {../$gfxDir/} }
		\usepackage[write,signatures]{frontespizio}
		
		\begin{document}
		\include{frontespizio}
		\end{document}
		" >> $tmpDir/$filename
		
	cd $tmpDir
	
	pdflatex -shell-escape "$filename"
	pdflatex -shell-escape "$name-frn.tex"
	
	mv "$name-frn.pdf" "../frontespizio.pdf"
	cd ..
	rm -rf $tmpDir
}

src_dir=tex/
name='tesi'

if [ "$1" = "-c" ]; then
	clearAll
	exit 0
elif [ "$1" = "-c-tex" ]; then
	clearTex
	exit 0
elif [ "$1" = "-c-gfx" ]; then
	clearGfx
	exit 0
elif [ "$1" = "-f" ]; then
	mkFrontespizio
	exit 0
fi

clearTex

cd tex

latex -shell-escape "$name.tex"
bibtex "$name"
latex -shell-escape "$name.tex"
latex -shell-escape "$name.tex"

pdflatex -shell-escape "$name-frn.tex"
pdflatex -shell-escape "$name.tex"

mv "$name.pdf" ../

exit 0

